GoogleCloudPlatform/php-docker

php-nginx/Dockerfile
php-nginx/build_deps.sh

This pull request modifies the build script to use the available PHP 7.0.0 final tar and verifies it.
It would be nice if you could merge and push it to the gcr registry.
I signed the CLA.

[TASK] Modify build to use PHP 7.0.0 final

---

php-nginx/composer.sh

Adds a configuration directive to ``composer.sh`` to clear the disabled functions to
allow execution of composer post-install hooks that rely on native processes.
Closes #15

[BUGFIX] Composer install should not disable functions

---

php-nginx/Dockerfile

Composer uses zip archives, if the requesting IP doesn't exceed
the GitHub API limit. If it does (which can happen easily if AppEngine
privisions a ComputeEngine builder with the same IP over and over
again), composer falls back to the VCS protocol. To make this
possible, the VCS binaries are needed inside the image.
May need a followup to consider SVN and Mercurial which are pretty
popular as well.
Long Term Solution is to check for an environment variable which
contains a GitHub oAuth Token and use it transparently in the image.
See: https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

[TASK] Install git into the docker image

---

php-nginx/Dockerfile

This patch ensures that the currently used PHP binaries
are always on the PATH variable, so subsequent commands
inside the container can run arbitrary commands as well
and don't have to care about where this image puts the
binaries.
See: https://docs.docker.com/engine/articles/dockerfile_best-practices/#env
Closes #19

[BUGFIX] PHP Binaries are not on $PATH

---

php-nginx/README.md

Besides suhosin, the main php.ini also uses disable_functions
to disable functions.
Other than on the command line, the value of that directive
needs some string to override the default.
Also mentions that you effectively replace the php.ini
completely.

[DOC] Mention how to enable disabled functions

---

php-nginx/README.md
php-nginx/composer.sh

A new environment variable `COMPOSER_GITHUB_OAUTH_TOKEN` can
now be used to let composer authenticate against the GitHub API on
behalf of the user. This allows the builder VM to always use the
`dist` packages and never fall back to the source method.
See https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

[FEATURE] Allow usage of a personal GitHub oAuth token

---

php-nginx/composer.sh

The following verbose composer output goes on for quite a while. The `--no-ansi` flag prevents this.

adds no-ansi to prevent verbose composer output

---

php-nginx/php-fpm.conf
php-nginx/php.ini

Also let php-fpm catches the stdout and stderr and stop picking up
php-fpm's access log.
Background: [The current fluentd configuration](https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/fluentd_logger/managed_vms.conf) only picks up certain file name patterns. We need to adapt our log file names to their pattern.

Changed the log file names so that our fluentd picks them.

---

php-nginx/composer.sh

All users that rely on composer scripts will need to extend
the Dockerfile and run the scripts manually in a second
build-step in their Dockerfile step.

Prevent composer from running any scripts on install

---

php-nginx/README.md
php-nginx/nginx.conf
php-nginx/php-fpm.conf

When using the unix socket, I often saw 502 GATEWAY error. The log shows something like this:
```
2016/03/12 10:25:23 [error] 18#0: *6016 connect() to unix:/var/run/php5-fpm.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 172.17.0.6, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "tmatsuo-wordpress.appspot.com"
```
First I tried to raise net.core.somaxconn with sysctl, but it raises an error like "read only file system". The next attempt is using TCP socket instead of unix socket. With my experiments, TCP sockets are much stabler upon high load.
See also #65

Use TCP for php-fpm and increase the number of workers.

---

php-nginx/Dockerfile
php-nginx/entrypoint.sh
php-nginx/nginx.conf
php-nginx/php-fpm.conf
testapps/php56_custom/php-fpm.conf
tests/CustomServingTest.php
tests/PHP5ExtensionsTest.php
tests/PHP7ExtensionsTest.php
tests/ServingTest.php

Also stopped using keepalive for fcgi in nginx.conf for test stability on travis, added debug output for local docker tests.
Fixes #71 
Related to #70

Allowing users to override php-fpm.conf.

---

php-nginx/README.md
php-nginx/build-scripts/build_php70.sh
testapps/php70_custom/web/apc.php
tests/PHP7ExtensionsTest.php

The module emulates the `apc_*` api methods for compatibility.

Add APC-BC for APCu backwards compatibility

---

php-nginx/Dockerfile

We should think about a way to store away the precompiled binaries in a trusted way somehow and only compile them when needed.

Upgrade PHP to 5.6.21 & 7.0.6

---

composer.json
composer.lock
scripts/install_test_dependencies.sh
scripts/run_test_suite.sh

According to FriendsOfPHP/PHP-CS-Fixer#1966, the availability of the
2.0-dev version as phar from dist was an accident.
This change adds the 2.0-alpha version through the project level dependencies.

Add php-cs-fixer through project level composer dependencies

---

php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh

GoogleCloudPlatform/php-docker#108 removed the possibility
to add PHP modules on build, which fails composer when there's
platform requirements such as `ext-gd`.
This patch re-adds the additonal scan folder.

Re-Add APP_DIR to ini scan folders

---

.php_cs
scripts/run_test_suite.sh

The build is failing on our jenkins with an error:
```
PHP Parse error:  syntax error, unexpected 'self' (T_STRING) in /var/lib/jenkins/jobs/php-nginx docker image/workspace/vendor/symfony/process/Process.php on line 538
```
I'd remove the vendor dir.

Removed vendor dir for cs check.

---

scripts/install_test_dependencies.sh

The new cloud SDK removed this config and it's erroring

Removed glcoud config set app/cloud_build

---

php-nginx/Dockerfile
tests/VersionTest.php

`PATH=${PHP_DIR}/bin:$PATH` needs to be on a separate line, as it uses env variables declared in the same line.

fixes PHP_DIR in PATH

---

README.md
e2e/EndToEndTest.php
php-nginx/README.md
scripts/run_e2e_tests.sh

We should use `gcloud app` instead of `gcloud preview app` which will go away soon.

Use `gcloud app` instead of `gcloud preview app`

---

scripts/build_images.sh

On environments like jenkins, or local workstations, `docker tag` will fail if there's always the tag.

Added `-f` option to `docker tag`

---

php-nginx/Dockerfile
php-nginx/composer.sh
php-nginx/entrypoint.sh

Under the cover it does many things:
* Temporarily enable shell for `www-data` user
* Run composer as `www-data`
* chown -R www-data.www-data ${APP_DIR}
* Permission changes regarding to this
* After running the `post-deploy-cmd`, disable the shell entry for `www-data` user and lock down the ${DOCUMENT_ROOT} (instead of locking down the entire ${APP_DIR})
However, looking at the surface, it is very simple:
* For simple customization, you can use `post-deploy-cmd` which is executed by `www-data`
* ${DOCUMENT_ROOT} is locked down to `root.www-data` 0550, but ${APP_DIR} is owned by `www-data` and it should be writable while it is still recommended to use `/tmp`
* Because www-data runs `composer install`, the files generated by the composer scripts can be accessible from the web app
My only …

Run composer as www-data.

---

php-nginx/Dockerfile
php-nginx/README.md
php-nginx/nginx-app.conf
tests/ServingTest.php

Note: with this image, we can just remove the `nginx-app.conf` in our most of the (probably all?) sample applications.

Provide a default nginx-app.conf

---

php-nginx/Dockerfile

The newest debian images for jessie (gcr.io/google-appengine/debian8:latest) now has all the extra env variables and ca-certs that were in base.
cc @dlorenc

Switch base image from base to debian8

---

php-nginx/php-nginx.yaml

License tests are automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/structure_tests/licenses_test.go (and the corresponding README) for more details.

adding license tests to structure tests

---

php-nginx/Dockerfile
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh

`--enable-memcached-sasl` option is actually not needed because the default is enabled. Now it's just installing from pecl which should be fine. It will also remove the warnings about missing so files at startup.

Version upgrades

---

deb-package-builder/debian/rules.in

This is intentionally not using the environment variable.
To change the `APP_DIR` env var, first you need to change it in our PHP
binaries, upload those packages, then change it in
`php-nginx/Dockerfile`.

Added /app to the --with-config-file-scan-dir option.

---

circle.yml
deb-package-builder/build.sh
deb-package-builder/debian/README.debian
deb-package-builder/debian/control.in
deb-package-builder/debian/rules.in
php-nginx/composer.sh

Before this PR, the name of the PHP debian packages are like:
gcp-php-5.6.30
gcp-php-7.0.15
and they provide virtual packages like gcp-php56, gcp-php70.
It turned out it is problematic when we have multiple patch versions
in our repo.
For example, if we have these two packages:
gcp-php-7.0.14_7.0.14-2
gcp-php-7.0.15_7.0.15-1
in a single repo, the following command fails:
```
$ apt-get -y install gcp-php70
```
because when there are multiple candidates for a virtual package, apt
can't decide which to pick, so it fails.
So we need to change the package names as follows:
gcp-php56_5.6.30-1
gcp-php70_7.0.15-1
so that our repo will have only one package for each minor versions.

Changed the name of the PHP debian packages.

---

php-nginx/fastcgi_params

It is more friendly for programs that expect the correct server name in `$_SERVER['SERVER_NAME']`.

Set SERVER_NAME to the same value as HTTP_HOST.

---

scripts/jenkins_build.sh

We're now reusing the CANDIDATE_TAG environment variable as the TAG environment variable. The TAG environment variable is used the the end-to-end test as the app version. This app version can only contain lowercase letters, digits, and hyphens. The fix here is to change the underscores to hyphens.

Make the CANDIDATE_TAG usable as cloud-build version [a-z0-9\-]

---

php-nginx/php-cli.ini
php-nginx/php.ini

I noticed the php cli is create a file named `STDERR`.
It worked for php-fpm because it can not open the file `STDERR` and fell back to stderr. We should use `/dev/stderr`.

Fixed a wrong error_log distination

---

deb-package-builder/extensions/memcached/build.sh

A new memcached package are uploaded to pecl, so we want to use it instead of using the git repo head

Use memcached from pecl for php 7.0 and 7.1

---

.travis.yml
check-versions/cloudbuild.yaml.in
check-versions/composer.json
check-versions/composer.lock
check-versions/phpunit.xml.dist
check-versions/tests/VersionTest.php
check-versions/tests/bootstrap.php
cloudbuild-test-runner/Dockerfile
scripts/check_versions.sh

Now it only checks micro versoins of php56, php70, php71, and nginx.
My plan is to run this on Travis with its Cron feature.

Adding tests for checking if the current versions are the latest

---

.travis.yml

Without this, the script for installing dependencies fails

Added an envvar to the travis config

---

deb-package-builder/extensions/functions.sh

If an extension's source is not available from PECL, you can use this
function to download and unzip the tarball from an arbitrary url.
Usage:
download_from_tarball <url> <version>
downlaod_from_tarball https://github.com/phalcon/cphalcon/archive/v3.0.4.tar.gz 3.0.4
It puts the source code in the same directory structure that downloading from PECL creates.

Add download_from_tarball function to the extension builders.

---

php-nginx/build-scripts/install_php56.sh
php-nginx/build-scripts/install_php70.sh
php-nginx/build-scripts/install_php71.sh
testapps/php56_extensions/Dockerfile.in
testapps/php70_extensions/Dockerfile.in
testapps/php71_extensions/Dockerfile.in

Automatically install our extensions built as debian packages when we install php.
This will allow the users to only have to enable them by adding a custom `php.ini` file rather than forcing them to create a Dockerfile.

Automatically install all of our pre-built extensions

---

scripts/build_images.sh

gcloud app deploy fails when there is a Dockerfile and cloudbuild.yaml in the app directory.

Rename the cloudbuild.yaml used for testing

---

scripts/jenkins_build.sh

We renamed the test image to php from php-nginx and updated the circle ci config previously.
This fixes the jenkins build (for testing new package versions)

Fix image name for jenkins build.

---

php-nginx/composer.sh

I have a plan for automatically configure `auto_prepend_file` for error reporting. When the `auto_prepend_file` for the error reporting is executed by root, internally it creates semaphore and shared kernel memory owned by root, and potentially it will prevent the daemon from running as www-data later.

Making sure the auto_prepend_file is not executed by root.

---

php-nginx/composer.sh

After removing the vendor dir, auto_prepend_file with our error reporting fails to bootstrap for those PHP calls.
For now I'd like to keep the Stackdriver integration just an opt-in feature with some custom config files. Later we'll design the automatic enabler with the Runtime Builder.

Added empty auto_prepend_file.

---

builder/gen-dockerfile/Dockerfile.in
builder/gen-dockerfile/cloudbuild.yaml.in
builder/gen-dockerfile/src/GenFiles.php
builder/gen-dockerfile/src/create_dockerfile.php
builder/gen-dockerfile/src/templates/Dockerfile.twig
builder/gen-dockerfile/tests/GenFilesTest.php
builder/php-latest.yaml

The `latest` tag in the `name` and `args` will be substituted with the exact sha value when we publish the builder definition file for pinning the pipeline to the specific image.

Runtime Builder improvement

---

php-nginx/php-fpm.conf

Now php-fpm throw away the output on stderr with the following configuration:
```
error_log = /dev/null
```
So the following code in php-fpm silently throws away the logs.
```
$stderr = fopen('php://stderr', 'w');
fwrite($stderr, 'Log to stderr' . PHP_EOL);
```

Sending php-fpm's error log to /dev/stderr

---

deb-package-builder/build_packages.sh

Add license.
If any steps fails, fail the build.
Increase the timeout for building all the extensions.
Fix the default versions of PHP that we're building.

Fix package build script.

---

php-nginx/Dockerfile
php-nginx/build-scripts/install_nginx.sh
php-nginx/entrypoint.sh
php-nginx/nginx.conf

This is an attempt to stop replacing the document root in `entrypoint.sh`.

Use envvar DOCUMENT_ROOT in nginx.conf

---

builder/gen-dockerfile/src/GenFilesCommand.php
builder/gen-dockerfile/src/templates/dockerignore.twig
builder/gen-dockerfile/tests/GenFilesCommandTest.php

* We also need to respect users' .dockerignore
* Docker image itself doesn't need app.yaml

Add app.yaml to the dockerignore with the runtime builder

---

php-base/Dockerfile
php-base/composer.sh

It is better to always use a directory which is outside of the webroot, guaranteed to be writable to `www-data` user.
Related: #251 and #263

Use /opt/composer for $COMPOSER_HOME

---

check-versions/tests/VersionTest.php

cloudbuild-test-runner is now built from the php onbuild image and no longer contains docker.
run the apt commands from inside the cloudbuild-test-runner.

Fix the version checker test

---

cloudbuild.yaml
integration-tests.yaml
scripts/build_images.sh
scripts/run_acceptance_tests.sh
testapps/build_pipeline/tests/tests/EndToEndTest.php
testapps/php71_e2e/tests/tests/EndToEndTest.php

Instead of implicitly relying on the currently configured project id, use the provided environment variable.
`$GOOGLE_PROJECT_ID` is the project where the images are built, `$E2E_PROJECT_ID` is where the project is deployed to for E2E tests.
In the E2E tests, we will set the current project id to the `E2E_PROJECT_ID`. The provided service account from the `SERVICE_ACCOUNT_JSON` should have enough permissions to deploy an App Engine application to the `E2E_PROJECT_ID`
Also changed the environment variable we look for in the E2E tests to `E2E_PROJECT_ID` to ease confusion.

Explicitly set the project id for the cloudbuild pipeline

---

testapps/build_pipeline/tests/tests/EndToEndTest.php

by allowing RUNTIME_BUILDER_ROOT env to be an empty string.
In PHP: 
```php
var_dump("" == false);
=> bool(true)
var_dump("" === false);
=> bool(false)
```

Allow acceptance test to use default pipeline

---

cloudbuild-test-runner/Dockerfile

Continue to use PHP 5.6 for now.

Test runner: use the php56 image instead of php-base

---

scripts/run_acceptance_tests.sh

Sorry it succeeded on my workstation with the same TAG, but fails with timestamped TAG on our jenkins.

Build the test-runner from the latest prod image for acceptance tests

---

deb-package-builder/build-packages.yaml
deb-package-builder/build_packages.sh
deb-package-builder/builder.yaml

Skip tagging the builder image as it's not needed by anything else
except this pipeline.

Build the debian package builder image as part of the cloudbuild.

---

deb-package-builder/build_packages.sh

Updating the default here rather than setting the environment variables for every build environment when building new versions.

update the debian sub-version for the php base packages (including gmp)

---

testapps/integration/app.yaml

since we're substituting in a newly built staging base runtime image, we need to use the custom runtime to deploy this app.
@tmatsuo

change runtime to custom in integration sample app

---

perf-dashboard/deployment-latency/cloudbuild.yaml
perf-dashboard/deployment-latency/tests/CollectDeploymentLatencyTest.php
scripts/record_deployment_latency.sh

Sorry, I noticed that it was always using xrt (it ran the command `false` and `true` instead).
With this change, it correctly uses the runtime builder.

Fixed a wrong command for setting app/use_runtime_builders config

---

builder/gen-dockerfile/src/Builder/Exception/GoogleCloudVersionException.php
builder/gen-dockerfile/src/Builder/GenFilesCommand.php
builder/gen-dockerfile/src/ValidateGoogleCloud.php
builder/gen-dockerfile/tests/GenFilesCommandTest.php
builder/gen-dockerfile/tests/test_data/stackdriver_no_composer/app.yaml
builder/gen-dockerfile/tests/test_data/stackdriver_no_google_cloud/app.yaml
builder/gen-dockerfile/tests/test_data/stackdriver_no_google_cloud/composer.json
builder/gen-dockerfile/tests/test_data/stackdriver_old_google_cloud/app.yaml
builder/gen-dockerfile/tests/test_data/stackdriver_old_google_cloud/composer.json
builder/gen-dockerfile/tests/test_data/stackdriver_simple/app.yaml
builder/gen-dockerfile/tests/test_data/stackdriver_simple/composer.json
php-base/Dockerfile
php-base/stackdriver-files/batch-daemon.conf
php-base/stackdriver-files/enable_stackdriver_integration.sh
php-base/stackdriver-files/stackdriver-errorreporting.ini

This PR adds `enable_stackdriver_integration` field in runtime_config. If it's set to true-ish value, the runtime builder will first check if there's a compatible google/cloud is there in `composer.json`, then add a command to enable stackdriver integration and set `IS_BATCH_DAEMON_RUNNING` env to true.

Adding automatic setup for stackdriver integration

---

deb-package-builder/extensions/stackdriver_trace/build.sh

Use the release archive from GitHub rather than master.
Also build v0.1.1 (fixes PHP 7.0 and segfaults for non-string labels)

Build stackdriver_trace extension from a GitHub release version archive.

---

builder/gen-dockerfile/src/Builder/Exception/RemovedEnvVarException.php
builder/gen-dockerfile/src/Builder/GenFilesCommand.php
builder/gen-dockerfile/tests/GenFilesCommandTest.php
builder/gen-dockerfile/tests/test_data/removed_env_var/app.yaml
php-base/build-scripts/composer.sh
php-onbuild/README.md

The runtime builder will throw an error when it's specified.
fixes #339

Removed `COMPOSER_GITHUB_OAUTH_TOKEN` env var.

---

php-base/nginx.conf

See also:
https://blog.percy.io/tuning-nginx-behind-google-cloud-platform-http-s-load-balancer-305982ddb340

Configure longer keepalive timeout for GCP loadbalancer.

---

deb-package-builder/libraries/cassandra-cpp-driver/build.sh

Build the cassandra-cpp-driver version 2.7.0
The latest version of the `cassandra` extension requires 2.7.0 of the `cassandra-cpp-driver` library.

Fix the cassandra extension build

---

testapps/integration-individual-packages/composer.json

It's needed because google/cloud-error-reporting needs grpc extension.

Added a necessary dep for the integration test

---

builder/gen-dockerfile/tests/GenFilesCommandTest.php

Somehow `setExpectedExceptionRegExp` changed the bahavior with the phpunit 5.7.23.
I think it's safer to use `expectException`.

Use expectException instead

---

deb-package-builder/build.sh

Seems like the download URL changes from RC version to version and there's no rule.

Correct download url for PHP 7.2.0RC5

---

deb-package-builder/build.sh
deb-package-builder/debian/rules.in

Compile PHP 7.2 with-sodium

---

testapps/php72_extensions/tests/LibSodiumTest.php

New PHP 7.2 package is available on cloud apt.

Re-enable the libsodium test on php 7.2

---

.gcloudignore
check-versions/tests/VersionTest.php
integration-tests.yaml

Our version checker that runs on a cron, does not verify the current PHP 7.2.x version.

Add php 7.2 version check

---

deb-package-builder/extensions/mongo/build.sh

The `$SHORT_VERSION` env variable is `56`, not `5.6`.
Verified that it does in fact build now.

Fix version check for building mongo

---

php-base/build-scripts/lockdown.sh

Removing loose `php-cli.ini` fails silently

---

deb-package-builder/extensions/redis/build.sh

4.0.0 has breaking changes. We will need a way to have both (similar to phalcon and swoole extensions).

Lock redis extension to 3.1.6

---

builder/gen-dockerfile/src/ValidateGoogleCloud.php
builder/gen-dockerfile/tests/GenFilesCommandTest.php
builder/gen-dockerfile/tests/test_data/stackdriver_old_logging/composer.json
builder/gen-dockerfile/tests/test_data/stackdriver_wildcard/app.yaml
builder/gen-dockerfile/tests/test_data/stackdriver_wildcard/composer.json

There are still some cases for false negative where the direct
constrant is ok and other indirect dependency has a problem.
Although the issue is not completely fixed, this logic change allows
more legitimate cases which has been failing with the previous code.
It will alleviate #426

Change the way we check the required version of the dependency

---

ubuntu-package-builder/build-packages.yaml

It's probably not required, but just for safety

Use different docker image name for ubuntu package builder

---

testapps/integration/test.yaml.in

The integration test uses a custom build pipeline. The build pipeline
now has extra arguments for the ubuntu image so we must provide them
here.

Fix the integration test.

---

cloudbuild-ubuntu.yaml

The debian gen-dockerfile image was being used for both Debian and Ubuntu pipelines. We need to push the ubuntu on in the ubuntu-cloudbuild.yaml

Push the gen-dockerfile image after building in cloudbuild

---

testapps/integration-individual-packages/composer.json

The combination of dependencies with the latest updates failed to load
a compatible gax version.
The integration app was throwing:
```
Uncaught Error: Class 'Google\ApiCore\CredentialsWrapper' not found in
/app/vendor/google/cloud-core/src/GrpcTrait.php:102
```

Update integration-individual package dependencies

---

perf-dashboard/deployment-latency/tests/CollectDeploymentLatencyTest.php

This is causing occasional timeouts on the system tracking deployments and you can only deploy ubuntu now.

Only track ubuntu16 deployment latency

---

builder/php-latest.yaml

kaniko builds container images from a Dockerfile, and enables future improvements to speed up builds by using the image registry as a layer cache (GoogleContainerTools/kaniko#300)

Use kaniko for building

---

package-builder/extensions/phalcon/build.sh
php-base/build-scripts/src/InstallExtensions.php

This change updates the build scripts to build the appropriate latest
versions of phalcon for each PHP version from PHP v7.0 onwards. Addresses #453

Allow building phalcon up to php v7.2

---

package-builder/debian/rules.in

As all the GAE deployments are atomic, we can compile with the flag `--enable-opcache-file`, and the user choose if he wants or not to enable it on the php.ini file.

Enable opcache file to improve CLI scripts speed

---

php-base/tests/InstallExtensionsTest.php

This test fails sometimes because php-base is pulling in all packages for all php versions, triggering some black listed combos

Removing flakey test

---

scripts/ubuntu-packages.cfg

Without this config file, the update-gcs script will fail to push the…correct package versions, which will cause the release steps to push the wrong versions.

Adding ubuntu-packages.cfg

---

builder/php-latest.yaml

The PHP runtime builder depends on this environment variable present. It is added by gcloud during the `gcloud app deploy` execution, but it's better to have it explicitly add it here.

Add app.yaml path to the environment variables

---

package-builder/extensions/timezonedb/build.sh

Addressing issue with php showing wrong TZ:
root@16464840edfa:/app# date
Mon Jan 27 17:57:20 UTC 2020
root@16464840edfa:/app# timedatectl set-timezone America/Sao_Paulo
root@16464840edfa:/app# date
Mon Jan 27 17:57:36 UTC 2020
root@16464840edfa:/app# timedatactl
bash: timedatactl: command not found
root@16464840edfa:/app# timedatectl
Local time: Mon 2020-01-27 14:57:47 -03
Universal time: Mon 2020-01-27 17:57:47 UTC
RTC time: Mon 2020-01-27 17:57:47
Time zone: America/Sao_Paulo (-03, -0300)
Network time on: no
NTP synchronized: yes
RTC in local TZ: no
root@16464840edfa:/app# php -a
Interactive shell
php > date_default_timezone_set('America/Sao_Paulo');
php > echo date("h:i:sa");
03:58:30pm

Update tz database

---

package-builder/extensions/protobuf/build.sh

We're pinning protobuf to version 3.10.0 in an attempt to give customers who are experiencing segfaults due to protobuf 3.11.2 issues a break until a protobuf fix can be released.

Pinning protobuf version to 3.10.0

---

builder/gen-dockerfile/src/Builder/GenFilesCommand.php
builder/gen-dockerfile/src/DetectPhpVersion.php
builder/gen-dockerfile/tests/GenFilesCommandTest.php
builder/php-latest.yaml

Back in May 2019 I deleted all the infrastructure for producing and using 5.6 and 7.0 images since they were EOL'd.  And this had the knock on effect of making it impossible to use those old images.  This change is intended to allow customers to specify the old images if they want, even though they can not be updated any longer.

Restoring the ability to specify php56 and php70 images

---

builder/gen-dockerfile/src/DetectPhpVersion.php

These files don't exist if we aren't wrapping up 5.6 and 7.0 images

Fixing build.  

---

package-builder/debian/rules.in
package-builder/libraries/libv8/debian/rules

Add --parallel flag to the debian rules. It seems to be accelerating the build (from ~41 mins to ~27 mins).

Set parallel in debian rules.
