.travis.yml
composer.json
composer.lock
php-nginx/Dockerfile
php-nginx/detect_php_version.php
testapps/php56/index.php
testapps/php56/pdo_sqlite.php
testapps/php56/phpinfo.php
testapps/php56_custom/Dockerfile
testapps/php56_custom/composer.json
testapps/php56_custom/composer.lock
testapps/php56_custom/nginx-app.conf
testapps/php56_custom/php.ini
testapps/php56_custom/web/index.php
testapps/php56_custom/web/pdo_sqlite.php
testapps/php56_custom/web/phpinfo.php
tests/CustomServingTest.php
tests/ServingTest.php
tests/VersionTest.php

Added functional tests.

---

.travis.yml
scripts/dump_credentials.php
scripts/run_e2e_tests.sh
tests/CustomServingTest.php
tests/ServingTest.php
tests/VersionTest.php

This PR is for running the test suite for our jenkins server.

Changed for running tests on jenkins.

---

php-nginx/Dockerfile
scripts/run_e2e_tests.sh

Upgraded to PHP 7.0.1.

---

php-nginx/README.md
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh
testapps/php56_custom/web/extensions.php
testapps/php70_custom/Dockerfile
testapps/php70_custom/composer.json
testapps/php70_custom/nginx-app.conf
testapps/php70_custom/php.ini
testapps/php70_custom/web/extensions.php
tests/Extensions.php
tests/PHP5ExtensionsTest.php
tests/PHP7ExtensionsTest.php

Adding some extensions including mongodb.

---

php-nginx/Dockerfile

Install mercurial and subversion for composer.

---

php-nginx/Dockerfile

Those include security updates and date back to January 07.
Do you plan to implement a process to keep track of such events?

Update PHP versions to 7.0.2 and 5.6.17

---

php-nginx/Dockerfile

@JustinBeckwith @bshaffer Can you take a quick look? It's for security update.

Upgrade to nginx-1.8.1.

---

e2e/EndToEndTest.php
php-nginx/README.md
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh
php-nginx/entrypoint.sh
php-nginx/php.ini
testapps/php56_custom/php.ini
testapps/php56_e2e/web/session.php
testapps/php56_e2e/web/session_save_handler.php
testapps/php70_custom/php.ini

This PR automatically enable memcached session on prod.
@bshaffer 
@sjlangley 
@cedricziel 
Please take a look and let me know what you think.

Enable memcached session automatically on prod.

---

php-nginx/composer.sh

Unset max_input_time when running composer.

---

scripts/install_test_dependencies.sh

Good bye builder-vms!
Fixes #61

Use cloud build for e2e testing.

---

php-nginx/Dockerfile

Upgrade to PHP 7.0.4.

---

php-nginx/Dockerfile

I should have waited a bit longer...

Upgrade to PHP 5.6.19.

---

php-nginx/php.ini

Removed libxml_disable_entity_loader from the blacklist.

---

php-nginx/Dockerfile

Changed the file owner to root.www-data.

---

php-nginx/entrypoint.sh
php-nginx/nginx.conf
tests/ServingTest.php

See:
http://nginx.org/en/docs/ngx_core_module.html#worker_processes

Use `auto` for worker_processes.

---

php-nginx/Dockerfile

Just talked with nginx guys and they recommend that we use mainline.

Upgrade to nginx-1.9.12.

---

php-nginx/Dockerfile
php-nginx/README.md
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh
php-nginx/build-scripts/php5-parse_str_harden.patch
php-nginx/build-scripts/php7-parse_str_harden.patch
php-nginx/php.ini
testapps/php56_custom/web/parse_str.php
testapps/php70_custom/web/parse_str.php
tests/CustomServingTest.php
tests/PHP7CustomServingTest.php

Patches parse_str to make the 2nd parameter mandatory.

---

php-nginx/composer.sh

Stop removing the `vendor` directory.

---

php-nginx/entrypoint.sh
php-nginx/nginx.conf
testapps/php56_nginx_conf/Dockerfile
testapps/php56_nginx_conf/nginx.conf
tests/CustomServingTest.php
tests/NginxConfTest.php

Also fixes a bug about wrong nginx.conf path.

Allow long requests by default.

---

php-nginx/Dockerfile
php-nginx/php-fpm.conf
php-nginx/supervisord.conf
tests/NginxConfTest.php
tests/VersionTest.php

Use /opt instead of /usr/local.

---

php-nginx/README.md
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh
php-nginx/entrypoint.sh
testapps/php56_custom_configs/Dockerfile
testapps/php56_custom_configs/app-supervisord.conf
testapps/php56_custom_configs/custom-supervisord.conf
testapps/php56_custom_configs/my-supervisord.conf
testapps/php56_custom_configs/nginx-custom.conf
testapps/php56_custom_configs/nginx-user.conf
testapps/php56_custom_configs/php-fpm-user.conf
testapps/php56_custom_configs/php-user.ini
tests/CustomConfigTest.php
tests/NginxConfTest.php

Env vars to change the custom config file name.

---

composer.json
composer.lock
scripts/run_test_suite.sh

Use stable version of php-cs-fixer.

---

e2e/EndToEndTest.php

Use gcloud preview app versions delete.

---

e2e/EndToEndTest.php
php-nginx/Dockerfile
php-nginx/README.md
php-nginx/entrypoint.sh
php-nginx/whitelist_functions.php
testapps/php56_custom/Dockerfile
testapps/php56_custom/php.ini
testapps/php56_custom/web/exec.php
testapps/php56_custom/web/phpinfo.php
testapps/php56_e2e/app.yaml
testapps/php56_e2e/php.ini
testapps/php56_e2e/web/exec.php
tests/CustomServingTest.php

To create appropriate ini file at runtime.

Added an envvar WHITELIST_FUNCTIONS.

---

circle.yml
scripts/dump_credentials.php
scripts/install_test_dependencies.sh
scripts/run_e2e_tests.sh
scripts/run_test_suite.sh
testapps/php56_custom/web/nginx-count.php
testapps/php56_custom/web/php-fpm-count.php
tests/CustomServingTest.php
tests/ServingTest.php

Migrating to circleci for PR hook.

Adding circleci configuration.

---

php-nginx/entrypoint.sh

addendum to #142 - misc code cleanup

removes COMPOSER_CMD

---

php-nginx/Dockerfile
php-nginx/build-scripts/build_php70.sh

Also cleaning up the installation processes for some extensions

Upgrade to PHP 5.6.26 and 7.0.10.

---

php-nginx/Dockerfile
php-nginx/build-scripts/build_php56.sh
php-nginx/build-scripts/build_php70.sh

Use deb packages generated by #178

Use memcached and jsonc debian packages

---

php-nginx/build-scripts/build_php56.sh

Verify the composer's installer

---

deb-package-builder/extensions/grpc/build.sh

@bshaffer Sorry #182 doesn't build grpc, so fixing it

Fixed grpc build

---

php-nginx/nginx.conf

Suppress health check logs

---

php-nginx/Dockerfile

Added -c option to supervisord in CMD

---

php-nginx/fastcgi_params
php-nginx/nginx.conf
testapps/php56_custom_configs/nginx-custom.conf
testapps/php56_custom_configs/tests/PHP56CustomConfigTest.php
testapps/php56_e2e/app.yaml
testapps/php56_e2e/tests/tests/EndToEndTest.php
testapps/php56_e2e/web/https-env.php
testapps/php56_nginx_conf/nginx.conf
testapps/php56_nginx_conf/tests/PHP56NginxConfTest.php

Set appropriate HTTPS envvar

---

php-nginx/README.md

Superseding #29
@bshaffer PTAL
FYI @cedricziel

Mention that the DOCUMENT_ROOT is changed to read-only

---

deb-package-builder/debian/rules.in

fixes #191 
See also:
http://php.net/manual/en/book.sem.php

Enable System V IPC family.

---

php-nginx/cloudbuild.yaml.in
scripts/build_images.sh

so that we can build with arbitrary apt repo.

Allow RUNTIME_DISTRIBUTION override

---

cloudbuild-test-runner/run_tests.sh

Added some appropriate options to `composer install`

---

cloudbuild-test-runner/Dockerfile

Use phpunit 5.7.x

---

php-nginx/composer.sh

Better warning for pinning the version

---

README.md
php-nginx/README.md

Updated the READMEs

---

php-nginx/build-scripts/install_php70.sh
php-nginx/build-scripts/install_php71.sh
scripts/install_test_dependencies.sh

Stop enabling apcu extension because it's redundant

---

testapps/integration/Dockerfile.in
testapps/integration/README.md
testapps/integration/app.yaml
testapps/integration/cloudbuild.yaml.in
testapps/integration/composer.json
testapps/integration/composer.lock
testapps/integration/web/index.php

This test application conforms to the proposed common integration framework test interface. Currently, only the root and logging tests are implemented as the exceptions and monitoring are not yet implemented in the google/cloud php library. This test also is not currently enabled yet, due to credential escalation bugs in the test runner.

Common integration test framework application

---

deb-package-builder/extensions/apcu_bc/build.sh

Not elegant, but it should work

Install the apcu-bc's config file back

---

deb-package-builder/Dockerfile
deb-package-builder/debian/control.in
deb-package-builder/debian/rules.in
deb-package-builder/extensions/phalcon/build.sh
testapps/php56_extensions/tests/GdTest.php
testapps/php70_extensions/tests/GdTest.php
testapps/php71_extensions/tests/GdTest.php

Adding freetype support to the GD extension

---

php-nginx/README.md

Move memcached to the pre-enabled section.

Extension docs cleanup.

---

php-nginx/composer.sh

Add `-m` flag for preserving env vars for composer install.

---

deb-package-builder/build_packages.sh

Our automated builder will build all the new packages next time it runs.

update php 7.1.5 and 7.0.19 for building debian packages

---

builder/gen-dockerfile/src/GenFilesCommand.php

Add app.yaml to .gitignore by default

---

scripts/build_images.sh

I was stupid and was not using the provided E2E_PROJECT_ID if provided

fix setting the E2E_PROJECT_ID

---

php-base/Dockerfile
php-base/entrypoint.sh
php-base/nginx-http.conf
php-base/nginx.conf
php-onbuild/README.md
testapps/php56_custom/nginx-http.conf
testapps/php56_custom/tests/PHP56CustomTest.php
testapps/php56_custom/web/readfile.php
testapps/php56_custom_configs/Dockerfile.in
testapps/php56_custom_configs/nginx-custom-http.conf
testapps/php56_custom_configs/tests/PHP56CustomConfigTest.php

Add a new envvar for the http block in nginx.conf

---

php-base/nginx.conf

Removed the error_log directive from the health check config

---

deb-package-builder/debian/rules.in
testapps/php56_extensions/tests/GmpTest.php
testapps/php70_extensions/tests/GmpTest.php
testapps/php71_extensions/tests/GmpTest.php

Add the gmp extension, included by default.

---

deb-package-builder/extensions/functions.sh

Use exponential backoff between each attempt. (sleeps 2**attempt seconds). Attempts 6 times (last attempt sleeps 64 seconds).

Add retry logic for downloading packages from pecl or via curl

---

testapps/integration/Dockerfile.in
testapps/integration/web/index.php

update sample app to conform to latest integration test spec

---

testapps/integration/Dockerfile.in
testapps/integration/app.yaml

Added the DOCUMENT_ROOT for the custom runtime

---

perf-dashboard/deployment-latency/cloudbuild.yaml
perf-dashboard/deployment-latency/composer.json
perf-dashboard/deployment-latency/composer.lock
perf-dashboard/deployment-latency/phpunit.xml.dist
perf-dashboard/deployment-latency/tests/CollectDeploymentLatencyTest.php
perf-dashboard/deployment-latency/tests/bootstrap.php
perf-dashboard/deployment-latency/tests/files/app.yaml
perf-dashboard/deployment-latency/tests/files/web/index.php
scripts/record_deployment_latency.sh

It doesn't need to be a phpunit test, but it's easy to utilize our test runner.

Added a script for collecting deployment latency of simple apps.

---

php-base/php-base.yaml

I think we need to streamline the process of the full release...

Removed the PHP micro versions in the structure test

---

perf-dashboard/deployment-latency/cloudbuild.yaml
perf-dashboard/deployment-latency/tests/CollectDeploymentLatencyTest.php
scripts/record_deployment_latency.sh

Now it uses app/use_runtime_builders config to change the gcloud
behavior. Added GCLOUD_TRACK envvar to specify the gcloud track.

Added GCLOUD_TRACK envvar for the record_deployment_latency

---

builder/gen-dockerfile/src/templates/Dockerfile.twig
builder/php-latest.yaml
testapps/build_pipeline/composer.json
testapps/build_pipeline/gcloud-env.php

Set GCLOUD_PROJECT envvar during the build.

---

deb-package-builder/build.sh
deb-package-builder/build_packages.sh

Also enable installing 7.2.0beta.

Update default PHP versions to 7.1.8-1, 7.0.22, 5.6.31 and 7.2.0beta2

---

integration-tests.yaml
testapps/build_pipeline/tests/tests/EndToEndTest.php
testapps/build_pipeline_php56/tests/tests/EndToEndTest.php
testapps/php71_e2e/tests/tests/EndToEndTest.php

Also use the specified vm image for php71_e2e

Echo the app.yaml before the deployments

---

builder/gen-dockerfile/src/Builder/GenFilesCommand.php
php-base/build-scripts/composer.sh
php-base/build-scripts/lockdown.sh
php-base/build-scripts/move-config-files.sh
php-base/stackdriver-files/enable_stackdriver_integration.sh

Add some user friendly echo messages.

Only use -x flag when BUILDER_DEBUG_OUTPUT env var is set.

---

deb-package-builder/debian/rules.in

Remove /app from the config-scan-dir

---

php-base/build-scripts/install_extensions.php
testapps/build_pipeline/composer.json
testapps/build_pipeline/tests/tests/EndToEndTest.php
testapps/build_pipeline/web/readfile.php

Only activate the extension when it's not loaded yet

---

builder/gen-dockerfile/src/Builder/GenFilesCommand.php
builder/gen-dockerfile/src/templates/Dockerfile.twig
builder/gen-dockerfile/tests/GenFilesCommandTest.php
builder/gen-dockerfile/tests/test_data/has_files/Dockerfile
php-base/build-scripts/composer.sh
php-onbuild/Dockerfile.in
testapps/builder_test/tests/DockerfileTest.php

Customizable composer flags

---

builder/gen-dockerfile/src/templates/Dockerfile.twig
php-base/build-scripts/entrypoint.sh

Checks the nginx config file syntax after moving user supplied config

---

php-onbuild/README.md

Added how to enable OPcache

---

testapps/integration-individual-packages/composer.json
testapps/integration/composer.json

The integration test started to fail. I filed a bug for that (https://github.com/GoogleCloudPlatform/google-cloud-php/issues/709).
The latest version should just work.

Updated google/cloud libraries to the current latest

---

builder/gen-dockerfile/src/DetectPhpVersion.php
php-base/build-scripts/dump_php_versions.sh

Unfortunately the previous changes are not enough

Remaining changes for supporting PHP 7.2

---

php-base/build-scripts/lockdown.sh

It's based on #377 
@jaitaiwan FYI
I'll surface this up to the runtime builder with another PR

Skip lockdown document root

---

deb-package-builder/extensions/opencensus/build.sh
deb-package-builder/extensions/stackdriver_debugger/build.sh

also use stackdriver_debugger devel channel

Use opencensus alpha

---

deb-package-builder/build.sh
deb-package-builder/debian/control.in

Add libsodium18 as debian package dependency for php72

---

php-base/build-scripts/install_php56.sh
php-base/build-scripts/install_php70.sh
php-base/build-scripts/install_php71.sh
php-base/build-scripts/install_php72.sh

Force creating symlinks for php-enmod and php-dismod

---

cloudbuild-ubuntu.yaml

Adding bigger machine type to build

---

testapps/build_pipeline/app.yaml
testapps/build_pipeline_std/app.yaml
testapps/builder_test/app.yaml
testapps/integration-individual-packages/app.yaml
testapps/integration/app.yaml
testapps/php72_e2e/app.yaml

Legacy health checks are no longer supported.  Adding split health checks to app.yaml files

Fixing integration tests.  

---

scripts/ubuntu-packages.cfg

Updating to version 7.2.29

---

scripts/ubuntu-packages.cfg

Updating PHP versions 7.3.23 and 7.2.34

Updating PHP versions 7.3.23 and 7.2.34
